baseURL = 'https://coldnoise.net/'
languageCode = 'en-us'
title = 'Cold Noise Blog'
theme = 'PaperMod'
enableEmoji = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # PaperMod specific settings
  defaultTheme = "auto" # auto, light, dark
  ShowReadingTime = true
  ShowShareButtons = false
  ShowCodeCopyButtons = true
  disableThemeToggle = false
  ShowToc = true

  # Site info
  copyright = "© 2025 John Boyd"
  description = "Personal blog by John Boyd"

  [params.editPost]
    URL = "https://github.com/phreaknik/coldnoise.net/tree/master/content"
    Text = "Suggest Changes" # edit text
    appendFilePath = true # to append file path to Edit link

  # PaperMod home page info mode
  [params.homeInfoParams]
    Title = "Cold Noise Blog"
    Content = "Personal blog by John Boyd"

  # Social links for PaperMod
  [[params.socialIcons]]
    name = "email"
    url = "mailto:hello@coldnoise.net"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/phreaknik"
  
[menu]
  [[menu.main]]
    name = "RSS"
    url = "/posts/index.xml"
    weight = 0
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Archive"
    url = "/archives/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 4
