baseURL = 'https://phreaknik.github.io/coldnoise.net/'
languageCode = 'en-us'
title = 'Thermal Noise H8r'
theme = 'plague'

[params]
  subtitle = "Your subtitle here"
  copyright = "© 2024 Your Name"
  
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
